spring:
  application:
    name: tay-java-app
  profiles:
    active: @spring.profiles.active@

#    build moi truong mvn clean package -P dev or test or prod,
#    thì đây là cách lấy giá trị được định nghĩa trong pom @spring.profiles.active@
