server:
  port: 8081
spring:
  config:
    activate:
      on-profile: test
openapi:
  service:
    api-docs: api-service
    title: API document
    version: v1.0.0
    server: http://localhost:${server.port}

